M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu20.04.1} date 2023. ápr. 27., csütörtök, 15:55:05 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-27T15:55:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1299
%
G90
G05
T1
X5.5571Y-2.7953
X6.0571Y-2.7953
T0
M30
